export const GET_ALL_POKEMONS = "GET_ALL_POKEMONS";
export const GET_ALL_POKEMONS_SUCCESS = "GET_ALL_POKEMONS_SUCCESS";
export const GET_ALL_POKEMONS_FAILED = "GET_ALL_POKEMONS_FAILED";
export const GET_ALL_POKEMONS_RESET = "GET_ALL_POKEMONS_RESET";
export const SET_COUNT = "SET_COUNT";
export const RESET_COUNT = "RESET_COUNT";

export const EXTEND_POKEMONS = "EXTEND_POKEMONS";
export const EXTEND_POKEMONS_SUCCESS = "EXTEND_POKEMONS_SUCCESS";
export const EXTEND_POKEMONS_FAILED = "EXTEND_POKEMONS_FAILED";
export const EXTEND_POKEMONS_RESET = "EXTEND_POKEMONS_RESET";
export const SET_EXTEND_COUNT = "SET_EXTEND_COUNT";
export const RESET_EXTEND_COUNT = "RESET_EXTEND_COUNT";

export const UPDATE_POKEMON = "UPDATE_POKEMON";
