export const GET_ALL_MY_POKEMONS = "GET_ALL_MY_POKEMONS";
export const GET_ALL_MY_POKEMONS_SUCCESS = "GET_ALL_MY_POKEMONS_SUCCESS";
export const GET_ALL_MY_POKEMONS_FAILED = "GET_ALL_MY_POKEMONS_FAILED";
export const GET_ALL_MY_POKEMONS_RESET = "GET_ALL_MY_POKEMONS_RESET";

export const FIND_POKEMON = "FIND_POKEMON";
export const FIND_POKEMON_SUCCESS = "FIND_POKEMON_SUCCESS";
export const FIND_POKEMON_FAILED = "FIND_POKEMON_FAILED";
export const FIND_POKEMON_RESET = "FIND_POKEMON_RESET";

export const CATCH_POKEMON = "CATCH_POKEMON";
export const CATCH_POKEMON_SUCCESS = "CATCH_POKEMON_SUCCESS";
export const CATCH_POKEMON_FAILED = "CATCH_POKEMON_FAILED";
export const CATCH_POKEMON_RESET = "CATCH_POKEMON_RESET";

export const RELEASE_POKEMON = "RELEASE_POKEMON";
export const RELEASE_POKEMON_SUCCESS = "RELEASE_POKEMON_SUCCESS";
export const RELEASE_POKEMON_FAILED = "RELEASE_POKEMON_FAILED";
export const RELEASE_POKEMON_RESET = "RELEASE_POKEMON_RESET";

export const RENAME_POKEMON = "RENAME_POKEMON";
export const RENAME_POKEMON_SUCCESS = "RENAME_POKEMON_SUCCESS";
export const RENAME_POKEMON_FAILED = "RENAME_POKEMON_FAILED";
export const RENAME_POKEMON_RESET = "RENAME_POKEMON_RESET";